# Generated by Django 2.2.1 on 2019-05-16 08:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='honorList',
        ),
        migrations.AddField(
            model_name='student',
            name='study_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='award',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Awardship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_get', models.DateTimeField(default=datetime.datetime(2019, 5, 16, 8, 50, 37, 73894, tzinfo=utc))),
                ('name', models.CharField(max_length=20)),
                ('Award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Award')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
        migrations.AddField(
            model_name='award',
            name='student',
            field=models.ManyToManyField(through='students.Awardship', to='students.Student'),
        ),
    ]
