# Generated by Django 2.2.1 on 2019-05-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20190516_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardship',
            name='date_get',
        ),
    ]
