# Generated by Django 2.2.1 on 2019-05-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_awardship_date_get'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='name',
            new_name='award_name',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='time',
            new_name='get_time',
        ),
        migrations.RenameField(
            model_name='awardship',
            old_name='name',
            new_name='awardship_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student_name',
        ),
        migrations.RemoveField(
            model_name='award',
            name='text',
        ),
        migrations.AddField(
            model_name='awardship',
            name='Awardship_detail',
            field=models.TextField(default='无详情'),
        ),
    ]
