# Generated by Django 2.2.1 on 2019-11-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20190520_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awardship',
            old_name='Award',
            new_name='award',
        ),
        migrations.RenameField(
            model_name='awardship',
            old_name='Awardship_detail',
            new_name='awardship_detail',
        ),
    ]
