# Generated by Django 2.2.1 on 2019-11-23 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20191121_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='study_id',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='学生学号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='award',
            name='award_name',
            field=models.CharField(max_length=30, verbose_name='赛事'),
        ),
        migrations.AlterField(
            model_name='awardship',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awardship_award', to='students.Award'),
        ),
        migrations.AlterField(
            model_name='awardship',
            name='awardship_name',
            field=models.CharField(max_length=20, verbose_name='获奖详情'),
        ),
        migrations.AlterField(
            model_name='awardship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awardship_student', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=10, verbose_name='学生姓名'),
        ),
    ]
