# Generated by Django 2.2.1 on 2019-11-23 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20191123_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['get_time'], 'verbose_name': '比赛'},
        ),
        migrations.AlterModelOptions(
            name='awardship',
            options={'verbose_name': '获奖奖项'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'verbose_name': '学生'},
        ),
        migrations.AlterField(
            model_name='award',
            name='get_time',
            field=models.DateTimeField(verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='award',
            name='student',
            field=models.ManyToManyField(through='students.Awardship', to='students.Student', verbose_name='参与学生'),
        ),
        migrations.AlterField(
            model_name='awardship',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awardship_award', to='students.Award', verbose_name='比赛'),
        ),
        migrations.AlterField(
            model_name='awardship',
            name='awardship_detail',
            field=models.TextField(blank=True, null=True, verbose_name='获奖详情'),
        ),
        migrations.AlterField(
            model_name='awardship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awardship_student', to='students.Student', verbose_name='获奖学生'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='学生邮箱'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_qq',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='学生qq'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_tel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='学生电话'),
        ),
    ]
