# Generated by Django 2.1.8 on 2020-06-02 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_course_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='course.Course', verbose_name='课程'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
