# Generated by Django 2.1.8 on 2020-06-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_credit',
            field=models.FloatField(verbose_name='绩点'),
        ),
    ]
